from __future__ import annotations

from typing import Protocol

from hanalpha.domain.models import AccountSnapshot, OrderEvent, OrderRequest, Quote


class Broker(Protocol):
    async def is_connected(self) -> bool: ...

    async def get_account_snapshot(self) -> AccountSnapshot: ...

    async def submit(self, order: OrderRequest, quote: Quote) -> list[OrderEvent]: ...

    async def process_quote(self, quote: Quote) -> list[OrderEvent]: ...

    async def cancel_all(self) -> list[OrderEvent]: ...

    async def flatten_all(self, quotes: dict[str, Quote]) -> list[OrderEvent]: ...
