from enum import StrEnum


class ArtifactType(StrEnum):
    IBKR_PREFLIGHT = "IBKR_PREFLIGHT"
    BURN_IN_SESSION = "BURN_IN_SESSION"
    BURN_IN_CORPUS = "BURN_IN_CORPUS"
    E1_SCENARIO_CASE = "E1_SCENARIO_CASE"
    E1_EVENT_RECEIPT = "E1_EVENT_RECEIPT"
    E1_FIXTURE_PERMIT = "E1_FIXTURE_PERMIT"
    E1_FIXTURE_RECEIPT = "E1_FIXTURE_RECEIPT"
    E1_QUOTE_CAPSULE = "E1_QUOTE_CAPSULE"
    E1_CLEANUP_RECEIPT = "E1_CLEANUP_RECEIPT"
    EXTERNAL_COST_RECEIPT = "EXTERNAL_COST_RECEIPT"
    GOLDEN_TAPE = "GOLDEN_TAPE"
    RESET_CASE = "RESET_CASE"
    CANCEL_CASE = "CANCEL_CASE"
    BRACKET_CASE = "BRACKET_CASE"
    ACCOUNT_PROOF = "ACCOUNT_PROOF"
    MARKET_CALENDAR_POLICY = "MARKET_CALENDAR_POLICY"
    LICENSE_RECEIPT = "LICENSE_RECEIPT"
    ENTITLEMENT_PROBE = "ENTITLEMENT_PROBE"
    RAW_SAMPLE_MANIFEST = "RAW_SAMPLE_MANIFEST"
    TIMESTAMP_AUDIT = "TIMESTAMP_AUDIT"
    REVISION_AUDIT = "REVISION_AUDIT"
    SYMBOLOGY_AUDIT = "SYMBOLOGY_AUDIT"
    SURVIVORSHIP_AUDIT = "SURVIVORSHIP_AUDIT"
    REVIEW_APPROVAL = "REVIEW_APPROVAL"


class ArtifactIdentityType(StrEnum):
    CONTENT_HASH = "CONTENT_HASH"
    MANIFEST_HASH = "MANIFEST_HASH"
